### ISSUE TITLE
All wormholes show up as shattered, no statics.

### ISSUE THREAD

**Issue by Drisker** [exodus4d/pathfinder#100]
As in topic. Fresh install, databases set up without problems, everything appears to be ok but every single wormhole is listed as shattered and shows no statics.

**Comment by exodus4d** [comment]
You probably have not imported some static data into your pathfinder DB. after setting up all the tables correctly.
https://github.com/exodus4d/pathfinder/blob/master/export/sql/pathfinder.sql

I think I forgot to mention this in the wiki. These data are necessary for static-WH information and jump-route configuration.

**Comment by Drisker** [comment]
That was it, fixed with simple 
`mysql -u pathfinder -p pathfinder < /pathfinder/export/sql/pathfinder.sql`

**Comment by sn0opy** [comment]
This is still not mentioned in the wiki or at least at a place not visible at first.
