### ISSUE TITLE
[BUG] Post upgrade - Internal server error on /setup

### ISSUE THREAD

**Issue by dnolen** [exodus4d/pathfinder#434]
Hi there, 

I just performed an upgrade to my apache based install to version 1.2.0 and when attempting to access the setup page I'm now seeing the attached error. 

SSO functionality works just fine,but accessing the setup portal fails with a argument error. 

![image](https://cloud.githubusercontent.com/assets/20019999/22617062/883c6a9c-ea89-11e6-8081-96e08ad59a4b.png)

**Comment by dnolen** [comment]
Related Argument errors are found in the apache log after the upgrade. 

[Sat Feb 04 08:20:00.238426 2017] [:error] [pid 1771] [client REDACTED] PHP Fatal error:  Call to undefined function Controller\\Api\\random_bytes() in /var/www/pathfinder/app/main/controller/api/map.php on line 621, referer: https://map.domain.com/map
[Sat Feb 04 08:21:33.566775 2017] [:error] [pid 3090] [client REDACTED] PHP Fatal error:  Call to undefined function Controller\\Api\\random_bytes() in /var/www/pathfinder/app/main/controller/api/map.php on line 621, referer: https://map.domain.com/map
[Sat Feb 04 08:22:21.372548 2017] [:error] [pid 2158] [client REDACTED] Argument 1 passed to lib\\Socket::setTtl() must be an instance of lib\\int, integer given, called in /var/www/pathfinder/app/main/lib/socket.php on line 56 and defined
[Sat Feb 04 08:23:33.385127 2017] [:error] [pid 1768] [client REDACTED] Argument 1 passed to lib\\Socket::setTtl() must be an instance of lib\\int, integer given, called in /var/www/pathfinder/app/main/lib/socket.php on line 56 and defined, referer: https://login.eveonline.com/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Fmap.domain.com%2Fsso%2FcallbackAuthorization&client_id=REDACTED CLIENT INFO

**Comment by dnolen** [comment]
![image](https://cloud.githubusercontent.com/assets/20019999/22617129/ec4a8130-ea8a-11e6-9845-7eb18908aedc.png)

**Comment by dkrotil** [comment]
@dnolen I have that error from above screenshot after upgrade to 1.2 very often. I will enabled debugging and look on logs if I find anything there.

**Comment by dkrotil** [comment]
And the mainstream is on NGINX, you are alone on this ... .

**Comment by dagoaty** [comment]
I plan to test the upgrade of my map this weekend. That is behind Apache so will report of I see the same error.

**Comment by exodus4d** [comment]
@dnolen you are on PHP 5.x 
`random_bytes()` is PHP 7 only.

Same for `Argument 1 passed to lib\Socket::setTtl() must be an instance of lib\int, integer given, called in /var/www/pathfinder/app/main/lib/socket.php on line 56 and defined`
"Static default parameters" are new in PHP7

The new requirements were already updated a few weeks ago: https://github.com/exodus4d/pathfinder/wiki/Requirements

**Comment by dnolen** [comment]
Well that would explain things. I'll toss php7 on the host and see how things go. 

I had issues with php7.1 giving me a depreciation error with mcrypt functions, so being that at the time the requirements didn't seem to require it I left it at php5. 

In future for a requirement change can you perhaps leave a warning on version upgrade notes so in case we don't check the reqs after the initial install its noted somewhere?

**Comment by exodus4d** [comment]
Yeah sorry about that. I just missed it in the [release notes}(https://github.com/exodus4d/pathfinder/releases/tag/v1.2.0). -> It´s updated now.

The Mcrypt warning is already fixed in `v1.2.0` (#422)

**Comment by dnolen** [comment]
Ya, that was my issue with previous releases. I'll have to schedule a scrub of php5.x versions from the host because after upgrading to 7.1 I'm still seeing internal server errors being thrown 

[Sat Feb 04 18:22:59.976219 2017] [:error] [pid 3730] [client USER_IP:50240] PHP Fatal error:  Call to undefined function Controller\\Api\\random_bytes() in /var/www/pathfinder/app/main/cont                                      roller/api/map.php on line 621, referer: https://map.domain.com/map

**Comment by dnolen** [comment]
/var/log/apache2# php -v
PHP 7.1.1-1+deb.sury.org~xenial+1 (cli) (built: Jan 20 2017 09:20:20) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by exodus4d** [comment]
Does your webserver use 7.1, too? Could you quick check /setup page and look for PHP-version?

**Comment by dnolen** [comment]
Ya, that would explain it. still shows 5.6 as the active running version. 
I'll have to get apache switched over somehow and scrub the older versions. 

This was so much easier with Nginx, but I can't use it do to tool reqs.

**Comment by exodus4d** [comment]
Feel free to ask quick questions like yours in you Slack chat. That´s more convenient than GitHub ;)

**Comment by dnolen** [comment]
Will do. I've rolled the host back to 1..1.7 for now. 
Thanks
