### ISSUE TITLE
Signature Reader losing information

### ISSUE THREAD

**Issue by Calavoow** [exodus4d/pathfinder#81]
The signature reader features is used to `ctrl+a`, `ctrl+v` in all the sigs in a wormhole. However, when some data has been added, e.g
```
XYZ Wormhole C247 blabla
```
but if the user then pastes
```
XYZ-123	Cosmic Signature			0%	6.00 AU
```
this will overwrite the available information for XYZ. I often copy all unkown sigs in a system (after it was already scanned) to check if there are any new signatures compared to our mapped data. But if this problem persists, it would overwrite all available information in the system.

**Comment by exodus4d** [comment]
Thanks for reporting this. Ill check it. This is definitely not intended and probably a bug

**Comment by Drisker** [comment]
Me and most of my scouts don't agree with this being a minor bug, for most its a game breaker that forces them to add only the new sig, either manually or paste it. It is the only problem mentioned as severe by 7 scouts we have in chain right now, which has to mean something. Expected behaviour would be preserving data for signatures that were on the list and adding signature that wasnt previously on the list.

Awesome piece of work, my corp loves it :)

**Comment by Tupsi** [comment]
ill second that (and close my other issue).

**Comment by atkinsj** [comment]
This is a massive issue.

**Comment by exodus4d** [comment]
Thanks for reporting!

Should be fixed in `v.1.0.0RC3`. The signature_type is not overwritten anymore.

**Comment by Tupsi** [comment]
this is still not working. With current dev type gets deleted and group gets reverted back to "unknown"

**Comment by exodus4d** [comment]
@Tupsi This should be fixed in #207
